# Data Preprocessing Tools

## Importing the libraries

In [5]:
shell_call <- function(command, ...) {
  result <- system(command, intern = TRUE, ...)
  cat(paste0(result, collapse = "\n"))
}
shell_call("git clone https://github.com/oscarfmg/machinelearning-az.git")
shell_call("cd ./machinelearning-az/ && git checkout develop")

Branch 'develop' set up to track remote branch 'develop' from 'origin'.

## Importing the dataset

In [10]:
dataset = read.csv('./machinelearning-az/update/Part1_DataPreprocessing/Section2_Part1_DataPreprocessing/R/Data.csv')

In [11]:
dataset

   Country Age Salary Purchased
1  France  44  72000  No
2  Spain   27  48000  Yes
3  Germany 30  54000  No
4  Spain   38  61000  No
5  Germany 40     NA  Yes
6  France  35  58000  Yes
7  Spain   NA  52000  No
8  France  48  79000  Yes
9  Germany 50  83000  No
10 France  37  67000  Yes

## Taking care of missing data

In [16]:
dataset$Age = ifelse(is.na(dataset$Age),
                     ave(dataset$Age, FUN = function(x) mean(x,na.rm=TRUE)),
                     dataset$Age)
dataset$Age

 [1] 44.00000 27.00000 30.00000 38.00000 40.00000 35.00000 38.77778 48.00000
 [9] 50.00000 37.00000

In [17]:
dataset$Salary = ifelse(is.na(dataset$Salary),
                     ave(dataset$Salary, FUN = function(x) mean(x,na.rm=TRUE)),
                     dataset$Salary)
dataset$Salary

 [1] 72000.00 48000.00 54000.00 61000.00 63777.78 58000.00 52000.00 79000.00
 [9] 83000.00 67000.00

## Encoding categorical data

### Encoding the Independent Variable

In [19]:
dataset$Country = factor(dataset$Country, levels = c('France','Spain','Germany'), labels = c(1,2,3))

In [20]:
dataset

   Country Age      Salary   Purchased
1  1       44.00000 72000.00 No
2  2       27.00000 48000.00 Yes
3  3       30.00000 54000.00 No
4  2       38.00000 61000.00 No
5  3       40.00000 63777.78 Yes
6  1       35.00000 58000.00 Yes
7  2       38.77778 52000.00 No
8  1       48.00000 79000.00 Yes
9  3       50.00000 83000.00 No
10 1       37.00000 67000.00 Yes

### Encoding the Dependent Variable

In [21]:
dataset$Purchased = factor(dataset$Purchased, levels = c('No','Yes'), labels=c(0,1))

In [22]:
dataset

   Country Age      Salary   Purchased
1  1       44.00000 72000.00 0
2  2       27.00000 48000.00 1
3  3       30.00000 54000.00 0
4  2       38.00000 61000.00 0
5  3       40.00000 63777.78 1
6  1       35.00000 58000.00 1
7  2       38.77778 52000.00 0
8  1       48.00000 79000.00 1
9  3       50.00000 83000.00 0
10 1       37.00000 67000.00 1

## Splitting the dataset into the Training set and Test set

In [23]:
install.packages('caTools')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘bitops’

In [24]:
library(caTools)

In [30]:
set.seed(123)
split = sample.split(dataset$Purchased,SplitRatio = 0.8)
split
training_set <- subset(dataset, split == TRUE)
testing_set <- subset(dataset, split == FALSE)

 [1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE

In [31]:
training_set

   Country Age      Salary   Purchased
1  1       44.00000 72000.00 0
2  2       27.00000 48000.00 1
3  3       30.00000 54000.00 0
4  2       38.00000 61000.00 0
5  3       40.00000 63777.78 1
7  2       38.77778 52000.00 0
8  1       48.00000 79000.00 1
10 1       37.00000 67000.00 1

In [32]:
testing_set

  Country Age Salary Purchased
6 1       35  58000  1
9 3       50  83000  0

## Feature Scaling

In [35]:
 training_set[,2:3] = scale(training_set[,2:3])
 testing_set[,2:3] = scale(testing_set[,2:3])

In [36]:
training_set

   Country Age         Salary     Purchased
1  1        0.90101716  0.9392746 0
2  2       -1.58847494 -1.3371160 1
3  3       -1.14915281 -0.7680183 0
4  2        0.02237289 -0.1040711 0
5  3        0.31525431  0.1594000 1
7  2        0.13627122 -0.9577176 0
8  1        1.48678000  1.6032218 1
10 1       -0.12406783  0.4650265 1

In [37]:
testing_set

  Country Age        Salary     Purchased
6 1       -0.7071068 -0.7071068 1
9 3        0.7071068  0.7071068 0